### ISSUE TITLE
[User] UserService. existsById(userId) 기능 요구

### ISSUE THREAD

**Issue by devYSK** [prgrms-be-devcourse/BE-03-BlackDogBucks#65]
### 건의 사항

주문에서 UserService를 이용하여 유저가 존재하는지의 여부를 확인하는 메소드가 필요합니다. 

![image](https://user-images.githubusercontent.com/41531594/215026325-afc25433-2a46-4de8-9aa7-8df026f5bf5d.png)

**Comment by rlarltj** [comment]
확인했습니다.
