### ISSUE TITLE
[Star, Coupon] 주문 수락시, star만큼 coupon을 생성하는 기능 필요 

### ISSUE THREAD

**Issue by devYSK** [prgrms-be-devcourse/BE-03-BlackDogBucks#80]
### 건의 사항
현재 주문 수락 로직을 구현하고 있습니다. 

userId나 orderId 등을 보내드릴 수 있습니다.

주문 수락 시,  보유하고 있는 star가 쿠폰으로 변환되어 저장되는 기능이 필요합니다. 

서비스 책임상 star가 적립되어 coupon으로 변하니, starService에 기능을 만들거나, Facade를 이용해야 할 것 같니다. 
책임에 맞게 위치가 적당한 서비스  호출 시, 내부적으로 로직이 계산되어 exchange된 만큼 쿠폰을 저장하는 로직 부탁드립니다. 

다음은 구현되어 있는 Star 엔티티의 로직입니다.
```java
class Star {

 public int exchangeCoupon() {
    int couponCount = count / 12;
    this.count %= 12;
    return couponCount;
  }
} 
```

필요한 파라미터가 있다면 말씀주세요.

**Comment by gw0215** [comment]
넵 확인했습니다.
